modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "noteblockapi"
version = "${version}"
displayName = "NoteBlockAPI"
authors = "xxmicloxx, michidk, koca2000, Luck, Gardelll"
description = '''
a developer interface to play nbs-files ingame
'''
#logoFile = ""

[[dependencies.noteblockapi]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.noteblockapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.noteblockapi]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "SERVER"
